workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic_AstroDots
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.inknmotion.app
      vars:
        BUNDLE_ID: com.inknmotion.app
        XCODE_WORKSPACE: ios/Runner.xcworkspace
        XCODE_SCHEME: Runner
      flutter: stable
      xcode: latest
    scripts:
      - name: Inject GoogleService-Info.plist
        script: |
          echo $IOS_FIREBASE_CONFIG | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Flutter analyze
        script: flutter analyze
      - name: Generate export options
        script: |
          cat > /Users/builder/export_options.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>teamID</key>
            <string>88U448KLJ8</string>
          </dict>
          </plist>
          EOF

      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  android-release:
    name: Android Release
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      vars:
        PACKAGE_NAME: com.inknmotion.ink_n_motion
      flutter: stable
      java: 17
    scripts:
      - name: Inject google-services.json
        script: |
          echo $ANDROID_FIREBASE_CONFIG | base64 --decode > $CM_BUILD_DIR/android/app/google-services.json
      - name: Set up Android keystore
        script: |
          echo $ANDROID_KEYSTORE | base64 --decode > $CM_BUILD_DIR/android/app/upload-keystore.jks
          cat <<EOF > $CM_BUILD_DIR/android/key.properties
          storePassword=$ANDROID_KEYSTORE_PASSWORD
          keyPassword=$ANDROID_KEYSTORE_PASSWORD
          keyAlias=$ANDROID_KEY_ALIAS
          storeFile=app/upload-keystore.jks
          EOF
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Flutter analyze
        script: flutter analyze
      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
