// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMF8vjO4BL1N5fetcEGGRmSi3niMkEU9U',
    appId: '1:346440485421:web:0496303ee5e4afccac86a4',
    messagingSenderId: '346440485421',
    projectId: 'vibr-8c484',
    authDomain: 'vibr-8c484.firebaseapp.com',
    storageBucket: 'vibr-8c484.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAERHqiNjtTakRkvGFS-1jwPcVAegT7YWc',
    appId: '1:346440485421:android:ba5c8366fa30ff88ac86a4',
    messagingSenderId: '346440485421',
    projectId: 'vibr-8c484',
    storageBucket: 'vibr-8c484.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFnNB1C11W-ymHzOxJypdP0OycACS29ek',
    appId: '1:346440485421:ios:c084745c81af60deac86a4',
    messagingSenderId: '346440485421',
    projectId: 'vibr-8c484',
    storageBucket: 'vibr-8c484.firebasestorage.app',
    iosClientId: '346440485421-ul8j6kodpvoljrvr7pkc422ot9v71232.apps.googleusercontent.com',
    iosBundleId: 'com.inknmotion.inkNMotion',
  );
}
